version: "3.9"

services:
  python:
    build:
      context: .
    ports:
      - "443:3000"
    depends_on:
      - redis
    env_file:
      - dotenv
    command: python -m app.app
    volumes:
      - /etc/letsencrypt/live/goerli-api.beradrome.com/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/goerli-api.beradrome.com/privkey.pem:/etc/ssl/private/privkey.pem:ro

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  syncer:
    build:
      context: .
    env_file:
      - dotenv
    command: sh -c 'python -m app.pairs.syncer'

volumes:
  redis_data:
