version: "3.9"

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/goerli-api.beradrome.com-0001/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /etc/letsencrypt/live/goerli-api.beradrome.com-0001/privkey.pem:/etc/ssl/private/privkey.pem:ro
    depends_on:
      - python

  python:
    build:
      context: .
    expose:
      - "3000"
    depends_on:
      - redis
    env_file:
      - dotenv
    command: python -m app.app

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  syncer:
    build:
      context: .
    env_file:
      - dotenv
    command: sh -c 'python -m app.pairs.syncer'

volumes:
  redis_data:
